/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_floodlight_brightness: 0
      i_pipeline_type: depth
      i_usb_speed: SUPER_PLUS
      i_nn_type: none
      i_publish_tf_from_calibration: True
      i_tf_imu_from_descr: 'true'
    left:
      i_fps: 90.0
      i_resolution: '400'
    right:
      i_fps: 90.0
      i_resolution: '400'
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_publish_synced_rect_pair: true
      i_right_rect_enable_feature_tracker: true