/rae:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_floodlight_brightness: 0
      i_pipeline_type: depth
      i_usb_speed: SUPER_PLUS
      i_nn_type: none
    left:
      i_fsync_continuous: true
      i_fsync_mode: INPUT
      i_resolution: '800P'
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 1
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
      i_fps: 10.0
      i_sensor_img_orientation: AUTO
    right:
      i_fsync_continuous: true
      i_fsync_mode: OUTPUT
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 2
      i_resolution: '800P'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
      i_fps: 10.0
    # imu:
    #   i_batch_report_threshold: 15
    #   i_max_batch_reports: 15
    #   i_enable_rotation: true
    #   i_message_type: IMU_WITH_MAG_SPLIT
    #   i_sync_method: COPY
    imu:
      i_batch_report_threshold: 5
      i_max_batch_reports: 5
      i_message_type: IMU
      i_sync_method: COPY
      i_gyro_freq: 100
      i_acc_freq: 100
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_publish_right_rect: true
      i_publish_left_rect: true
      i_right_rect_enable_feature_tracker: true
